find_package(WM5 COMPONENTS Wm5Mathematics Wm5Core REQUIRED) # Wm5Physics Wm5Imagics 

list(APPEND ALL_INCLUDE_DIRECTORIES ${WM5_INCLUDE_DIR})
list(APPEND ALL_LIBRARIES ${WM5_LIBRARIES})
list(APPEND ALL_LIBRARY_DIRS ${WM5_LINK_DIRECTORIES})
