// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _GeomFill_GuideTrihedronAC_A_HeaderFile
#define _GeomFill_GuideTrihedronAC_A_HeaderFile

#include <vector>

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>

#include <Handle_Approx_CurvlinFunc.hxx>
#include <Standard_Real.hxx>
#include <Handle_Adaptor3d_HCurve.hxx>
#include <GeomFill_TrihedronWithGuide.hxx>
#include <Handle_GeomFill_TrihedronLaw.hxx>
#include <Handle_GeomFill_GuideTrihedronAC.hxx>
#include <Standard_Boolean.hxx>
#include <Standard_Integer.hxx>
#include <GeomAbs_Shape.hxx>
class Approx_CurvlinFunc;
class Adaptor3d_HCurve;
class Standard_OutOfRange;
class Standard_ConstructionError;
class GeomFill_TrihedronLaw;
class gp_Vec;
class TColStd_Array1OfReal;

DEFINE_STANDARD_HANDLE(GeomFill_GuideTrihedronAC_A, GeomFill_TrihedronWithGuide)

//! Trihedron in  the  case of a sweeping along a guide  curve.
//! defined by curviline  absciss
class GeomFill_GuideTrihedronAC_A : public GeomFill_TrihedronWithGuide
{

public:

  
  Standard_EXPORT GeomFill_GuideTrihedronAC_A(const Handle(Adaptor3d_HCurve)& guide);
  
  Standard_EXPORT virtual   void SetCurve (const Handle(Adaptor3d_HCurve)& C) ;
  
  Standard_EXPORT virtual   Handle(GeomFill_TrihedronLaw) Copy()  const;
  
  Standard_EXPORT virtual   Handle(Adaptor3d_HCurve) Guide()  const;
  
  Standard_EXPORT virtual   Standard_Boolean D0 (const Standard_Real Param, gp_Vec& Tangent, gp_Vec& Normal, gp_Vec& BiNormal) ;
  
  Standard_EXPORT virtual   Standard_Boolean D1 (const Standard_Real Param, gp_Vec& Tangent, gp_Vec& DTangent, gp_Vec& Normal, gp_Vec& DNormal, gp_Vec& BiNormal, gp_Vec& DBiNormal) ;
  
  Standard_EXPORT virtual   Standard_Boolean D2 (const Standard_Real Param, gp_Vec& Tangent, gp_Vec& DTangent, gp_Vec& D2Tangent, gp_Vec& Normal, gp_Vec& DNormal, gp_Vec& D2Normal, gp_Vec& BiNormal, gp_Vec& DBiNormal, gp_Vec& D2BiNormal) ;
  
  //! Returns  the number  of  intervals for  continuity
  //! <S>.
  //! May be one if Continuity(me) >= <S>
  Standard_EXPORT virtual   Standard_Integer NbIntervals (const GeomAbs_Shape S)  const;
  
  //! Stores in <T> the  parameters bounding the intervals
  //! of continuity <S>.
  //!
  //! The array must provide  enough room to  accomodate
  //! for the parameters. i.e. T.Length() > NbIntervals()
  Standard_EXPORT virtual   void Intervals (TColStd_Array1OfReal& T, const GeomAbs_Shape S)  const;
  
  //! Sets the bounds of the parametric interval on
  //! the function
  //! This determines the derivatives in these values if the
  //! function is not Cn.
  Standard_EXPORT virtual   void SetInterval (const Standard_Real First, const Standard_Real Last) ;
  
  //! Get average value of M(t) and V(t) it is usfull to
  //! make fast approximation of rational  surfaces.
  Standard_EXPORT virtual   void GetAverageLaw (gp_Vec& ATangent, gp_Vec& ANormal, gp_Vec& ABiNormal) ;
  
  //! Say if the law is Constant
  Standard_EXPORT virtual   Standard_Boolean IsConstant()  const;
  
  //! Say if the law is defined, only by the 3d Geometry of
  //! the setted Curve
  //! Return False by Default.
  Standard_EXPORT virtual   Standard_Boolean IsOnlyBy3dCurve()  const;
  
  Standard_EXPORT virtual   void Origine (const Standard_Real OrACR1, const Standard_Real OrACR2) ;

  // RK
  void setSubCurveLaws(const std::vector<Handle(GeomFill_GuideTrihedronAC_A)>& subCurveLaws);


  DEFINE_STANDARD_RTTI(GeomFill_GuideTrihedronAC_A)

protected:




private: 


  Handle(Approx_CurvlinFunc) myGuideAC;
  Standard_Real Lguide;
  Handle(Approx_CurvlinFunc) myCurveAC;
  Standard_Real L;
  Handle(Adaptor3d_HCurve) myCurve;
  Standard_Real UTol;
  Standard_Real STol;
  Standard_Real Orig1;
  Standard_Real Orig2;

  std::vector<Handle(GeomFill_GuideTrihedronAC_A)> _subCurveLaws;
  std::vector<double> _subCurveParameters;
};







#endif // _GeomFill_GuideTrihedronAC_A_HeaderFile
